---
jobs:
  test:
    docker:
      - image: quay.io/mongodb-build/molecule
    steps:
      - checkout
      - setup_remote_docker
      - run: mv ~/project ~/$CIRCLE_PROJECT_REPONAME
      - run: echo "cd ~/$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
      - run: molecule test

  release:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: npm-cache
      - run: npm install @semantic-release/changelog -D
      - run: npm install @semantic-release/git -D
      - save_cache:
          key: npm-cache
          paths:
            - node_modules
      - run: npx semantic-release
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test
